### ISSUE TITLE
Allow the Director to update the cache if it fails

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelicanfs#2]
When a mapper is created for a file url ("root") the director should find a working url for the value and pass it to the mapper to be used.

If, for some reason, this ever fails (file not found, cache not reachable), we want the director to find a new value.  Each function that uses the current cache url should have a decorator function that attempts the call using the http fsspec call, catches a ConnectionError or FileNotFoundError, and then has the director find a working cache to use and updates it.

This may also require creating our own get_mapper function which calls the fsspec.get_mapper, but also contains it's own version of the current url attached to the "root" namespace path so it can be updated as needed. Or even the creation of a PelFSMap to wrap the FSMap as the FSMap throws errors if the url is changed on it.

Ideally we want the key in a PelFSMap to be the namespace path and to also store the latest good cache for the namespace to try. This is to not constantly ask the director for a cache when using an FSMap. The root also needs to be a namespace path and not a url because if the url fails/we want to try a different cache, the FSMap seems to complain because it won't match the key.

**Comment by bbockelm** [comment]
This is done as part of #39.

The `PelicanFileSystem` object now has a namespace cache with a mapping of a prefix to a list of valid caches.  On every failure, the cache list is updated to remove the broken cache.
