### ISSUE TITLE
Loosen requirements to use lower bound pins instead of exact match

### ISSUE THREAD

**Issue by duncanmmacleod** [PelicanPlatform/pelicanfs#56]
The current runtime requirements are pinned using exact match operators for everything:

https://github.com/PelicanPlatform/pelicanfs/blob/7bb7b4fc11451bdb18bf52a4995ba1ad9615dec2/setup.py#L37-L46

This will make this package hard to integrate into larger software environments. Is it reasonable to replace the `==` exact match operators with `~=X.Y` version constraints?

**Comment by duncanmmacleod** [comment]
For example, `aiohttp==3.9.4` is (for an unknown reason) not available from conda-forge, so this project cannot be packaged for that distribution right now.

**Comment by turetske** [comment]
Done!
